### PR TITLE
Switching to main branch of RSocrata

### PR DESCRIPTION
**Pull request by geneorama**
Removed reference to sprint7 branch of RSocrata in `CODE/00_Startup.R`

Modified the import data files (listed below) to match previous data format.
`CODE/11_business_download.R`
`CODE/12_crime_download.R`
`CODE/13_food_inspection_download.R`
`CODE/14_garbage_download.R`
`CODE/15_sanitation_download.R`

### CODE REVIEW

**Comment by geneorama** [comment]
@tomschenkjr Please let me know if you want to review / have comments.  Thanks!

**Comment by cash** [comment]
Is this going to be pulled in?

**Comment by geneorama** [comment]
There were a few changes that had been started in RSocrata that were [just pulled in] (https://github.com/Chicago/RSocrata/pull/86).  The RSocrata changes will simplify the import process here.  I'm revising this pull request now.

**Comment by geneorama** [comment]
Just updated the files (major simplifications for the most part) and tested that the files could run all the way through. 

I also made major changes to one section of the README

**Comment by geneorama** [comment]
@tomschenkjr By the way, I don't know why this says that I haven't signed the CLA, I actually did sign it a while ago to make the failure notices disappear.

**Pull request merged**
