### PR TITLE
calculate days saved on average with the new schedule

### PR DESCRIPTION
**Pull request by cash**
Added a function that computes the schedule based on a score column (renamed glm_pred) and calculates the mean time saved for finding violations. It gives the answer 7.4 days.

### CODE REVIEW

**Comment by cash** [comment]
@geneorama any comments on this new function to calculate days saved

**Comment by geneorama** [comment]
Looking at this today, I'll be making comments shortly.

**Comment by geneorama** [comment]
@cash Thank you for these contributions.

It's a very good idea to break the model evaluation out into a script, and it's something that I wish I would have done a long time ago.

I went through the code and after some editing, I realized / remembered that you can do the date difference very simply with the following:

```R
simulated_date_diff_mean <- function(dates, scores, pos) {
    require(data.table)
    
    ##--------------------------------------------------------------------------
    ## Create base data
    ##--------------------------------------------------------------------------
    ## Assemble components into a data.table for convenience
    dat <- data.table(date=dates, score=scores, pos)
    
    ##--------------------------------------------------------------------------
    ## Add simulated result
    ##--------------------------------------------------------------------------
    ## This assumes inspectors would perform the same number of inspections per
    ## day, as they had in their original schedule.
    
    ## The simulated date is a vector of the original dates in sequential
    ## order, but matched to the original data ordered by score.
    dat <- dat[order(-score), simulated_date := dat[order(date), date]][]
    
    ## The time difference is the difference between the original date and 
    ## the simulated date, for occurrences that are "positive"
    mean_diff <- dat[pos==1, mean(date - simulated_date)]
    
    ##--------------------------------------------------------------------------
    ## Return average date difference
    ##--------------------------------------------------------------------------
    return(mean_diff)
}
```

However, I couldn't bring myself to delete all the binning logic, especially because that is the basis for other parts of the evaluation.  

So, I ended up with another function (based on your code) 
```R
simulated_bin_summary <- function(dates, scores, pos) {
    require(data.table)
    
    ##--------------------------------------------------------------------------
    ## Create base data
    ##--------------------------------------------------------------------------
    ## Assemble components into a data.table for convenience
    dat <- data.table(date=dates, score=scores, pos)
    
    ##--------------------------------------------------------------------------
    ## Add simulated result
    ##--------------------------------------------------------------------------
    
    ## This assumes inspectors would perform the same number of inspections per
    ## day, as they had in their original schedule.
    
    ## The simulated date is a vector of the original dates in sequential
    ## order, but matched to the original data ordered by score.
    dat <- dat[order(-score), simulated_date := dat[order(date), date]][]
    
    ##--------------------------------------------------------------------------
    ## Simulate inspector assignment to bins according to score
    ##--------------------------------------------------------------------------
    
    ## Create bin summary of results
    
    ## Caluclate original counts / day
    ## Note: Using `keyby` forces the result to be sorted, which is necessary
    ##       for the cumulative summation.
    bins <- dat[i = TRUE,
                j = list(POS = sum(pos), 
                         .N), 
                keyby = date]
    bins <- bins[ , NTOT := cumsum(N)][]
    bins <- bins[ , POSTOT := cumsum(POS)][]
    
    ## Caluclate simulated counts / day
    ## Note: Here we key by the simulated date
    bins_sim <- dat[i = TRUE,
                    j = list(POS = sum(pos), 
                             .N), 
                    keyby = simulated_date]
    bins_sim <- bins_sim[ , NTOT := cumsum(N)][]
    bins_sim <- bins_sim[ , POSTOT := cumsum(POS)][]
    
    setcolorder(bins, c("date", "N", "NTOT", "POS", "POSTOT"))
    bins <- merge(bins, 
                  bins_sim[i = TRUE,
                           j = list(POS_SIM = POS,
                                    POSTOT_SIM = POSTOT),
                           keyby = list(date = simulated_date)],
                  "date")
    return(bins)
}
```

As I was admiring the "bin" results and thinking about how much information it contains, it dawned on me that the date difference is actually just a weighted average which can be obtained from the bin result.

The weighted average calculation would look like this:
```R
datTest <- dat[iiTest]
bins <- datTest[ , simulated_bin_summary(Inspection_Date, score, criticalFound)]
bins[ , sum(as.integer(date) * POS) / sum(POS)] - 
    bins[ , sum(as.integer(date) * POS_SIM) / sum(POS_SIM)]
# [1] 7.437984
```

I want to thank you for a few things, and explain why I made so many changes.

First, I really appreciate that you stuck with `data.table`, and followed the convention of putting the function in the right spot, and everything else. Secondly, I want to say that the `sapply` with `.I` thing was really clever.  I'm still not 100% sure why it works.  As I've already said, the main idea of breaking out the evaluation logic has been needed for some time.

I also want to apologize that it's taken so long to accept this pull request, but there were a lot of changes happening on the data import step (again) that involved the RSocrata dependency, and those issues had to be resolved for other reasons, with more urgency.

I took some notes about why I was making the changes, which hopefully you'll find useful.  This is everything I can think of that took me from your function to my two modified functions. 

Some notes:
 + In general there were several redundant objects, which makes the code logic more difficult to understand, test, and debug.  So, I refactored the code to consolidate objects.
 + The first call to `table` can be accomplished natively within `data.table` by a call to `.N`, which is more consistent within the syntax of the project.
 + Passing in vectors rather than a `data.table` is less convenient because you have to type more, but there are several reasons that it's better to call in vectors rather than the data.table object
  + Since `data.table` objects are modified in place, I try not to pass them into functions.  It's too easy to modify the `data.table` object unintentionally.  Even though you're in the function environment, the modifications are "in place" meaning that the `data.table` is modified in the global environment.
  + There is no need to remember the format / class / name requirements for the table in the future
  + The user can use any container and isn't stuck with just `data.table` (e.g. `data.frame`, `matrix`, `list`, etc)
  + Passing in vectors rather than a `data.table` has the downside that the vectors must be in the same order, and a failure to maintain that order can result in an error that can't be identified within the function.  I have no solution for this, except to document the requirement.  I think this risk is worth the benefit of using vectors.
 + This function is a great idea and something that I hope to use elsewhere.  So, I want it to be as general as possible.  So,
  + The length check should be outside the function (or perhaps passed in as an argument)
  + The names should be as general as possible (i.e. I changed the "critical found" indicator to `pos` which is more consistent with other ML libraries).

Again, thank you.

Gene

**Comment by geneorama** [comment]
Also, I'm going to remove a lot of the evaluation code that's currently in the 30 script, and replace it with your function.

**Comment by geneorama** [comment]
@cash  Also, I would be very interested in your commentary about the next series of changes.  So, I'm going to make the changes in a branch and propose them as a pull request and invite your commentary (and criticism!).

**Pull request merged**
