### PR TITLE
Remove Socrata API key req, Fix docs

### PR DESCRIPTION
**Pull request by fgregg**

### CODE REVIEW

**Comment by fgregg** [comment]
Rebased of Gene's PR.

**Comment by tomschenkjr** [comment]
@geneorama do you think removing the SoDA token will impact the ability to download the business license data set given the throttling issues we had?

**Comment by fgregg** [comment]
I didn't have any problems downloading the data with these scripts.

**Comment by geneorama** [comment]
I think that Socrata has had some changes in the months since we initially
started this project, and each change seems to have made it easier and
faster to download data.

At one point the token really helped, but with the improvements maybe it's
no longer needed.  It seemed to matter the most when multiple were
downloading the same thing, i.e. if we were doing something at open hack
night.

**Comment by tomschenkjr** [comment]
I was able to run it without any issues (I know I was pushing on the token thing early in this). Given we're using the RSocrata from the dev channel (which now uses JSON by default), which is much faster, it may have been solved as @geneorama mentioned.

I've merged the pull request. We can roll this back if performance is an issue.

**Pull request merged**
